name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          # Ajoutez d'autres plateformes si nécessaire, par exemple:
          # - StandaloneLinux64
          # - StandaloneOSX

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Unity version
      uses: game-ci/unity-setup@v2
      with:
        unity-version: 2020.3.10f1 # Remplacez par votre version d'Unity

    - name: Build project
      uses: game-ci/unity-builder@v2
      with:
        projectPath: ./ # Chemin vers votre projet Unity
        unityVersion: 2022.3.5f1 # Remplacez par votre version d'Unity
        targetPlatform: ${{ matrix.targetPlatform }}
        # Si vous avez un fichier de licence, ajoutez:
        # customImage: unityci/editor:2020.3.10f1-windows
        # licenseFile: .github/workflows/Unity_v20XX.X.XXXX.ulf

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build-${{ matrix.targetPlatform }}
        path: build/${{ matrix.targetPlatform }}
